[versions]
kotlin = "1.9.21"
build-jdk = "11"
test-jdk = "11"

api = "2023.1"
core = "2023.6"

junit = "5.9.3"
jacoco = "0.8.7"

[libraries]
openapi-processor-api = { module = "io.openapiprocessor:openapi-processor-api", version.ref = "api" }
openapi-processor-test = { module = "io.openapiprocessor:openapi-processor-test", version.ref = "core" }
openapi-processor-core = { module = "io.openapiprocessor:openapi-processor-core", version.ref = "core" }
openapi-processor-parser-api = { module = "io.openapiprocessor:openapi-processor-core-parser-api", version.ref = "core" }
openapi-processor-parser-swagger = { module = "io.openapiprocessor:openapi-processor-core-parser-swagger", version.ref = "core" }
openapi-processor-parser-openapi4j = { module ="io.openapiprocessor:openapi-processor-core-parser-openapi4j", version.ref = "core" }

jackson-bom = "com.fasterxml.jackson:jackson-bom:2.16.0"
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind" }
jackson-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }

checker = "org.checkerframework:checker:3.41.0"
jimfs = "com.google.jimfs:jimfs:1.3.0"
slf4j = "org.slf4j:slf4j-api:2.0.9"
logback = "ch.qos.logback:logback-classic:1.4.14"

kotest-bom = "io.kotest:kotest-bom:5.8.0"
kotest-runner = { module = "io.kotest:kotest-runner-junit5" }
kotest-datatest = { module = "io.kotest:kotest-framework-datatest" }
mockk = "io.mockk:mockk:1.13.8"

groovy-bom = "org.apache.groovy:groovy-bom:4.0.17"
spock = "org.spockframework:spock-core:2.3-groovy-4.0"

plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin"}
plugin-checker = "org.checkerframework:checkerframework-gradle-plugin:0.6.5"
plugin-outdated = "com.github.ben-manes:gradle-versions-plugin:0.46.0"

[bundles]
jackson = ["jackson-databind", "jackson-yaml", "jackson-kotlin"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
nexus = { id = "io.github.gradle-nexus.publish-plugin", version = "1.3.0" }
jacoco = { id = "org.barfuin.gradle.jacocolog", version = "3.1.0" }
versions = { id = "com.github.ben-manes.versions", version = "0.50.0" }
sonar = { id = "org.sonarqube", version = "4.4.1.3373" }
