[versions]
kotlin = "1.8.21"
build-jdk = "11"
target-jdk = "11"

junit = "5.9.3"
jacoco = "0.8.7"

[libraries]
openapi-processor-api = "io.openapiprocessor:openapi-processor-api:2021.1"
openapi-processor-test = "io.openapiprocessor:openapi-processor-test:2023.2"
openapi-processor-core = "io.openapiprocessor:openapi-processor-core:2023.2"

jackson-bom = "com.fasterxml.jackson:jackson-bom:2.15.2"
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind" }
jackson-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }

checker = "org.checkerframework:checker:3.34.0"
jimfs = "com.google.jimfs:jimfs:1.2"
slf4j = "org.slf4j:slf4j-api:2.0.7"
logback = "ch.qos.logback:logback-classic:1.4.7"

kotest-bom = "io.kotest:kotest-bom:5.6.2"
kotest-runner = { module = "io.kotest:kotest-runner-junit5" }
kotest-datatest = { module = "io.kotest:kotest-framework-datatest" }
mockk = "io.mockk:mockk:1.13.5"

groovy-bom = "org.apache.groovy:groovy-bom:4.0.12"
spock = "org.spockframework:spock-core:2.3-groovy-4.0"

plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin"}
plugin-checker = "org.checkerframework:checkerframework-gradle-plugin:0.6.5"
plugin-outdated = "com.github.ben-manes:gradle-versions-plugin:0.46.0"

[bundles]
jackson = ["jackson-databind", "jackson-yaml", "jackson-kotlin"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
nexus = { id = "io.github.gradle-nexus.publish-plugin", version = "1.3.0" }
jacoco = { id = "org.barfuin.gradle.jacocolog", version = "3.1.0" }
versions = { id = "com.github.ben-manes.versions", version = "0.46.0" }
sonar = { id = "org.sonarqube", version = "4.0.0.2929" }
