/*
 * Copyright © 2020 https://github.com/openapi-processor/openapi-processor-micronaut
 * PDX-License-Identifier: Apache-2.0
 */

package io.openapiprocessor.micronaut.writer.java

import io.openapiprocessor.core.writer.java.SimpleWriter
import io.openapiprocessor.spring.Version
import java.io.Writer

import java.time.Instant

var HEADER = """
    |/*
    | * DO NOT MODIFY - this class was auto generated by openapi-processor-micronaut
    | *
    | * ${Version.version}
    | * ${Instant.now()} 
    | * https://docs.openapiprocessor.io/micronaut
    | */
    |
""".trimMargin()

/**
 * Writer for a simple header of the generated interfaces & classes.
 */
class HeaderWriter: SimpleWriter {

    override fun write(target: Writer) {
        target.write (HEADER)
    }

}
