/*
 * Copyright © 2020 https://github.com/openapi-processor/openapi-processor-micronaut
 * PDX-License-Identifier: Apache-2.0
 */

package io.openapiprocessor.micronaut.processor

import io.openapiprocessor.micronaut.writer.java.HeaderWriter
import com.github.hauner.openapi.test.ProcessorTestBase
import com.github.hauner.openapi.test.TestSet
import io.openapiprocessor.micronaut.writer.java.HeaderWriterKt
import org.junit.BeforeClass

class EndToEndBase extends ProcessorTestBase {

    EndToEndBase (TestSet testSet) {
        super (testSet)
    }

    @BeforeClass
    static void setConstantHeaderWriterText () {
        // set a "fixed" header, we don't want moving version/date/time parts

        HeaderWriterKt.HEADER = """\
/*
 * DO NOT MODIFY - this class was auto generated by openapi-processor-micronaut
 *
 * test
 * time
 * https://docs.openapiprocessor.io/micronaut 
 */

"""
    }

}
